<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Application User Model
	|--------------------------------------------------------------------------
	|
	| The class name of your Application's user model
	|
	*/
	
	'user_model' => 'User',

	/*
	|--------------------------------------------------------------------------
	| Notifications Table Name
	|--------------------------------------------------------------------------
	|
	| The name of the table used to store notifications in
	|
	*/

	'table_name' => 'Notifications',

	/*
	|--------------------------------------------------------------------------
	| Notifications Route Prefix
	|--------------------------------------------------------------------------
	|
	| Set the prefix for routes generated by this package
	|
	*/

	'package_prefix' => 'notifications',

	/*
	|--------------------------------------------------------------------------
	| Notifications Route Filter
	|--------------------------------------------------------------------------
	|
	| Set the filter(s) to be used for notifications routes
	|
	*/

	'route_filter' => 'auth'

);